# Generated by Django 4.2.4 on 2023-09-04 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('ADD', '+'), ('SUBTRACT', '-'), ('MULTIPLY', '*'), ('DIVIDE', '/'), ('POWER', '**'), ('SQRT', 'sqrt'), ('FACTORIAL', '!'), ('MODULUS', '%'), ('INT_DIVIDE', '//')], max_length=10)),
                ('first_number', models.FloatField()),
                ('second_number', models.FloatField(blank=True, null=True)),
                ('result', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
